adding swagger spec and endpoints (Practice 1)
VikaAbysova/Node.js_Course_Practice pull request #1
Opened 2023-10-11 20:37 UTC by VikaAbysova

2023-10-13 10:54 UTC, ihor-osadchyi-dev requested changes

2023-10-13 10:54 UTC, ihor-osadchyi-dev commented on swagger.yaml
As I understand task requirements, Swagger JS Docs should be used for describing endpoints. 
For example like this:
```
/**
 * @openapi
 * /:
 *   get:
 *     description: Welcome to swagger-jsdoc!
 *     responses:
 *       200:
 *         description: Returns a mysterious string.
 */
app.get('/', (req, res) => {
  res.send('Hello World!');
});
```

2023-10-13 12:45 UTC, VikaAbysova commented on swagger.yaml
Hello Ihor! 
Actually you are rigth. At first I wrote it in the code context like in your example, but then I decided to move these describes in separate file to avoid mixing. Should I fix it?

2023-10-13 12:53 UTC, ihor-osadchyi-dev commented on swagger.yaml
Let's follow the requirement. If you want to make index file smaller, better to move routes to separate files. For example, `health-check` could be moved to `health-check.router.js` file and such for other routes.

```
// health-check.router.js

const express = require('express');
const router = express.Router();

// Define the route for the health check
router.get('/health-check', (req, res) => {
  res.status(200).json({ message: 'Server is running...' });
});

module.exports = router;
```
Use the health-check router for the '/health-check' route
```
app.use('/health-check', healthCheckRouter);
```

2023-10-13 13:52 UTC, VikaAbysova commented on swagger.yaml
Ok, thanks' a lot!

2023-10-16 16:30 UTC, IhorOsadchyi commented on src/index.js
> +const PORT = 3000;
These two const better to place after block of require section. Currently it is not affecting functionality but separation block of imports and local variables is a good practice. 

```suggestion
```

2023-10-16 16:30 UTC, ihor-osadchyi-dev commented on src/index.js
> +
```suggestion

const app = express();
const PORT = 3000;
```

2023-10-16 16:33 UTC, IhorOsadchyi commented on src/index.js
> +const swaggerUi = require('swagger-ui-express');
Also it's better to sort imported modules by it's type. First external and after it local. This is a small element among those that makes the code more readable.

```suggestion
const swaggerJSDoc = require('swagger-jsdoc');
const swaggerUi = require('swagger-ui-express');

const healthCheckRouter = require('./routes/health-check.router');
const userRouter = require('./routes/user.router');
```

2023-10-16 16:34 UTC, ihor-osadchyi-dev reviewed
Made small additional comment not related to functionality but codestyle.

2023-10-17 05:57 UTC, ihor-osadchyi-dev approved these changes

2023-10-17 11:52 UTC, merged